# Generated by Django 4.2.16 on 2024-09-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
